dbt_project:
  target: dev
  outputs:
    dev:
      type: mysql
      server: localhost
      port: 3306
      schema: analytics
      username: #########
      password: #########
      ssl_disabled: True
    prod:
      type: mysql
      server: localhost
      port: 3306
      schema: analytics
      username: #########
      password: #########!

      ssl_disabled: True