dbt_project:
  target: dev
  outputs:
    dev:
      type: mysql
      server: localhost
      port: 3306
      schema: analytics
      username: root
      password: Rachael510!
      ssl_disabled: True
    prod:
      type: mysql
      server: localhost
      port: 3306
      schema: analytics
      username: graeme
      password: Oremotsuyoi510!

      ssl_disabled: True